import json
import time
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse

from app.auth.dependencies import require_api_key
from app.auth.service import consume_budget
from app.cache import semantic_cache
from app.core.config import settings
from app.core.cost import get_cost, get_usage
from app.core.exceptions import (
    BudgetExceededError,
    ModelAliasNotFoundError,
)
from app.core.model_resolver import model_resolver
from app.core.rate_limit_dependency import check_rate_limit
from app.core.router import routing_engine
from app.schemas.chat import ChatCompletionRequest
from app.usage.usage_service import record_usage


def _extract_stream_usage(
    chunk: str,
) -> dict[str, Any] | None:
    """
    Extract the latest usage object from an OpenAI-compatible SSE chunk.

    Supports either:
      - standard streaming `usage`
      - Prism-normalized `prism_usage`

    Providers may emit usage only in the final streaming event.
    """
    for line in chunk.splitlines():
        line = line.strip()

        if not line.startswith("data:"):
            continue

        payload = line[5:].strip()

        if not payload or payload == "[DONE]":
            continue

        try:
            event = json.loads(payload)
        except (TypeError, ValueError):
            continue

        if not isinstance(event, dict):
            continue

        usage = event.get("prism_usage")

        if usage is None:
            usage = event.get("usage")

        if not isinstance(usage, dict):
            continue

        return {
            "prompt_tokens": int(
                usage.get("prompt_tokens", 0) or 0
            ),
            "completion_tokens": int(
                usage.get("completion_tokens", 0) or 0
            ),
            "total_tokens": int(
                usage.get("total_tokens", 0) or 0
            ),
            "cost": float(
                usage.get("cost", 0) or 0
            ),
        }

    return None


def _zero_usage() -> dict[str, Any]:
    return {
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0,
        "cost": 0.0,
    }


router = APIRouter()


def _request_id(request: Request) -> str | None:
    """
    Read the request ID generated by middleware, when available.
    """

    return getattr(
        request.state,
        "request_id",
        None,
    )


def _cost_header(cost: float) -> str:
    return f"{float(cost):.10f}"


def _usage_values(
    response: dict[str, Any],
) -> dict[str, Any]:

    usage = get_usage(response)

    return {
        "prompt_tokens": usage[
            "prompt_tokens"
        ],
        "completion_tokens": usage[
            "completion_tokens"
        ],
        "total_tokens": usage[
            "total_tokens"
        ],
        "cost": usage["cost"],
    }


@router.post(
    "/v1/chat/completions",
)
async def chat_completions(
    request: Request,
    chat_request: ChatCompletionRequest,
    identity: dict = Depends(
        require_api_key
    ),
):

    started_at = time.perf_counter()

    remaining = await check_rate_limit(
        identity
    )

    request_id = _request_id(
        request
    )

    try:

        # ---------------------------------------------------------
        # Convert messages
        # ---------------------------------------------------------

        messages = [
            message.model_dump()
            for message in chat_request.messages
        ]

        # ---------------------------------------------------------
        # Resolve aliases.
        #
        # auto -> fast/smart
        # ---------------------------------------------------------

        resolved_alias = (
            model_resolver.resolve_alias(
                chat_request.model,
                messages,
            )
        )

        alias = model_resolver.resolve(
            resolved_alias,
            messages,
        )

        application_id = identity[
            "id"
        ]

        application_name = identity[
            "application_name"
        ]

        # ---------------------------------------------------------
        # Streaming
        #
        # Forward every chunk immediately. We do not buffer the
        # generated content. The wrapper only inspects SSE metadata
        # so that final token/cost usage can be recorded after the
        # upstream stream completes.
        # ---------------------------------------------------------

        if chat_request.stream:

            stream_result = (
                await routing_engine.stream(
                    alias=resolved_alias,
                    model=alias.model,
                    messages=messages,
                )
            )

            async def tracked_stream():
                stream_usage = _zero_usage()
                stream_completed = False

                try:
                    async for chunk in stream_result.stream:
                        extracted_usage = (
                            _extract_stream_usage(
                                chunk
                            )
                        )

                        if extracted_usage is not None:
                            stream_usage = extracted_usage

                        # Send the original provider chunk immediately.
                        yield chunk

                    stream_completed = True

                except Exception:
                    latency_ms = (
                        time.perf_counter()
                        - started_at
                    ) * 1000

                    record_usage(
                        application_id=application_id,
                        application_name=application_name,
                        model=stream_result.model or alias.model,
                        provider=stream_result.provider,
                        status="failed",
                        latency_ms=latency_ms,
                        prompt_tokens=(
                            stream_usage["prompt_tokens"]
                        ),
                        completion_tokens=(
                            stream_usage["completion_tokens"]
                        ),
                        total_tokens=(
                            stream_usage["total_tokens"]
                        ),
                        cost=stream_usage["cost"],
                        request_id=request_id,
                        cache_type="bypass",
                        fallback_used=(
                            stream_result.fallback_used
                        ),
                    )

                    raise

                finally:
                    if stream_completed:
                        latency_ms = (
                            time.perf_counter()
                            - started_at
                        ) * 1000

                        cost = max(
                            0.0,
                            float(stream_usage["cost"]),
                        )

                        # Streaming usage becomes known only after the
                        # provider emits its final usage event. Consume
                        # the actual cost atomically at completion.
                        #
                        # A true pre-admission budget check for streaming
                        # requires an estimated cost from the pricing table;
                        # that will be handled by the pricing/budget stage.
                        budget_consumed = True

                        if cost > 0:
                            budget_consumed = (
                                consume_budget(
                                    key_id=application_id,
                                    cost=cost,
                                )
                            )

                        record_usage(
                            application_id=application_id,
                            application_name=application_name,
                            model=stream_result.model or alias.model,
                            provider=stream_result.provider,
                            status=(
                                "success"
                                if budget_consumed
                                else "failed"
                            ),
                            latency_ms=latency_ms,
                            prompt_tokens=(
                                stream_usage[
                                    "prompt_tokens"
                                ]
                            ),
                            completion_tokens=(
                                stream_usage[
                                    "completion_tokens"
                                ]
                            ),
                            total_tokens=(
                                stream_usage[
                                    "total_tokens"
                                ]
                            ),
                            cost=cost,
                            request_id=request_id,
                            cache_type="bypass",
                            fallback_used=(
                                stream_result.fallback_used
                            ),
                        )

            return StreamingResponse(
                tracked_stream(),
                media_type="text/event-stream",
                headers={
                    "Cache-Control": "no-cache",
                    "X-Accel-Buffering": "no",
                    "X-Prism-Provider": (
                        stream_result.provider
                    ),
                    "X-Prism-Cache": "BYPASS",
                    "X-Prism-Fallback": str(
                        stream_result.fallback_used
                    ).lower(),
                    # The final stream cost is known only after the
                    # final usage event, so the initial HTTP header is
                    # necessarily zero. Persisted usage contains the
                    # actual final cost when the provider supplies it.
                    "X-Prism-Cost-USD": "0.0000000000",
                    "X-Prism-Application": (
                        application_name
                    ),
                    "X-Prism-Resolved-Model": (
                        resolved_alias
                    ),
                    "X-RateLimit-Remaining": str(
                        remaining
                    ),
                },
            )

        # ---------------------------------------------------------
        # Semantic cache lookup
        # ---------------------------------------------------------

        if settings.semantic_cache_enabled:

            cache_result = (
                await semantic_cache.get(
                    application_id=(
                        application_id
                    ),
                    model=alias.model,
                    messages=messages,
                )
            )

            if cache_result is not None:

                latency_ms = (
                    time.perf_counter()
                    - started_at
                ) * 1000

                # Cache hits represent zero provider cost.
                record_usage(
                    application_id=(
                        application_id
                    ),
                    application_name=(
                        application_name
                    ),
                    model=alias.model,
                    provider="cache",
                    status="success",
                    latency_ms=latency_ms,
                    prompt_tokens=0,
                    completion_tokens=0,
                    total_tokens=0,
                    cost=0.0,
                    request_id=request_id,
                    cache_type=cache_result["cache_type"],
                    fallback_used=False,
                )

                return JSONResponse(
                    content=cache_result[
                        "response"
                    ],
                    headers={
                        "X-Prism-Provider": "cache",
                        "X-Prism-Cache": (
                            cache_result[
                                "cache_type"
                            ].upper()
                        ),
                        "X-Prism-Fallback": "false",
                        "X-Prism-Cost-USD": "0.0000000000",
                        "X-Prism-Application": (
                            application_name
                        ),
                        "X-Prism-Resolved-Model": (
                            resolved_alias
                        ),
                        "X-RateLimit-Remaining": str(
                            remaining
                        ),
                    },
                )

        # ---------------------------------------------------------
        # Provider execution
        # ---------------------------------------------------------

        result = await routing_engine.execute(
            alias=resolved_alias,
            model=alias.model,
            messages=messages,
            stream=False,
        )

        usage = _usage_values(
            result.response
        )

        cost = float(
            usage["cost"]
        )

        # ---------------------------------------------------------
        # Atomically consume actual provider cost.
        # ---------------------------------------------------------

        if cost > 0:

            budget_consumed = (
                consume_budget(
                    key_id=application_id,
                    cost=cost,
                )
            )

            if not budget_consumed:

                latency_ms = (
                    time.perf_counter()
                    - started_at
                ) * 1000

                # Log the rejected request without charging the
                # monthly budget.
                record_usage(
                    application_id=(
                        application_id
                    ),
                    application_name=(
                        application_name
                    ),
                    model=result.model or alias.model,
                    provider=result.provider,
                    status="failed",
                    latency_ms=latency_ms,
                    prompt_tokens=(
                        usage[
                            "prompt_tokens"
                        ]
                    ),
                    completion_tokens=(
                        usage[
                            "completion_tokens"
                        ]
                    ),
                    total_tokens=(
                        usage[
                            "total_tokens"
                        ]
                    ),
                    cost=cost,
                    request_id=request_id,
                    cache_type="miss",
                    fallback_used=result.fallback_used,
                )

                raise BudgetExceededError(
                    "Monthly budget exceeded"
                )

        # ---------------------------------------------------------
        # Store successful provider response in semantic cache.
        # ---------------------------------------------------------

        if settings.semantic_cache_enabled:

            await semantic_cache.set(
                application_id=(
                    application_id
                ),
                model=alias.model,
                messages=messages,
                response=result.response,
            )

        # ---------------------------------------------------------
        # Record successful request.
        # ---------------------------------------------------------

        latency_ms = (
            time.perf_counter()
            - started_at
        ) * 1000

        record_usage(
            application_id=application_id,
            application_name=application_name,
            model=result.model or alias.model,
            provider=result.provider,
            status="success",
            latency_ms=latency_ms,
            prompt_tokens=(
                usage[
                    "prompt_tokens"
                ]
            ),
            completion_tokens=(
                usage[
                    "completion_tokens"
                ]
            ),
            total_tokens=(
                usage[
                    "total_tokens"
                ]
            ),
            cost=cost,
            request_id=request_id,
            cache_type="miss",
            fallback_used=result.fallback_used,
        )

        # ---------------------------------------------------------
        # Response
        # ---------------------------------------------------------

        return JSONResponse(
            content=result.response,
            headers={
                "X-Prism-Provider": (
                    result.provider
                ),
                "X-Prism-Cache": "MISS",
                "X-Prism-Fallback": str(
                    result.fallback_used
                ).lower(),
                "X-Prism-Cost-USD": (
                    _cost_header(cost)
                ),
                "X-Prism-Application": (
                    application_name
                ),
                "X-Prism-Resolved-Model": (
                    resolved_alias
                ),
                "X-RateLimit-Remaining": str(
                    remaining
                ),
            },
        )

    except BudgetExceededError as exc:

        raise HTTPException(
            status_code=402,
            detail=str(exc),
        ) from exc

    except ModelAliasNotFoundError as exc:

        raise HTTPException(
            status_code=400,
            detail=str(exc),
        ) from exc

    except Exception:

        # Record unexpected non-provider failures.
        latency_ms = (
            time.perf_counter()
            - started_at
        ) * 1000

        record_usage(
            application_id=identity["id"],
            application_name=(
                identity[
                    "application_name"
                ]
            ),
            model=(
                chat_request.model
            ),
            provider=None,
            status="failed",
            latency_ms=latency_ms,
            request_id=request_id,
            cache_type="miss",
            fallback_used=False,
        )

        raise